### PR TITLE
Dandancheeseandham patch 1

### PR DESCRIPTION
**Pull request by dandancheeseandham**
A chunk of doc updates

### CODE REVIEW

**Comment by dandancheeseandham** [comment]
So I've created a folder called "wiki to contain what is essentially the wiki. I figured there may be other major sections or parts of the main site.
Other than that it's just a start at migrating the dokuwiki

**Comment by lostapathy** [comment]
This looks good.  I think after we get everything migrated from the legacy wiki, we should probably think about how to carve the content that's coming across into /wiki/ into subdirectories like /guide/, /components/, that kind of thing.

**Comment by kraegar** [comment]
Will we be able to have publicly editable areas, and locked areas? or will
it all be by pull request?

**Comment by lostapathy** [comment]
@kraegar I think the thinking was to have all edits done via PR.  But that said, you can propose an edit and create the PR all in-browser in a workflow not too far off a traditional wiki.

**Pull request merged**
